name: 'ObjC CocoaPods'

on:
  push:
    paths:
    - '.github/workflows/objc_cocoapods.yml'
    - 'Protobuf.podspec'
    - 'objectivec/**'
    - '!objectivec/DevTools/**'
    - '!objectivec/ProtocolBuffers_*.xcodeproj/**'
    - '!objectivec/Tests/**'
  pull_request:
    paths:
    - '.github/workflows/objc_cocoapods.yml'
    - 'Protobuf.podspec'
    - 'objectivec/**'
    - '!objectivec/DevTools/**'
    - '!objectivec/ProtocolBuffers_*.xcodeproj/**'
    - '!objectivec/Tests/**'

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  pod-lib-lint:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        # Add back 'watchos'. See CocoaPods/CocoaPods#11558
        PLATFORM: ["ios", "macos", "tvos"]
        CONFIGURATION: ["Debug", "Release"]
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - name: Pod lib lint
      run:  |
        pod lib lint --verbose \
          --configuration=${{ matrix.CONFIGURATION }} \
          --platforms=${{ matrix.PLATFORM }} \
          Protobuf.podspec
